// components/RootLayout.tsx

import React from 'react';
import Link from 'next/link';
import { Inter } from 'next/font/google';

import type { Metadata } from 'next';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <style>{inter.css}</style>
      </head>
      <body className={inter.className}>
        <nav>
          <ul>
            <li>
              <Link href="/menu1">
                菜单1
              </Link>
              <ul>
                <li>
                  <Link href="/menu1/submenu1">
                    子菜单1
                  </Link>
                </li>
                <li>
                  <Link href="/menu1/submenu2">
                    子菜单2
                  </Link>
                </li>
              </ul>
            </li>
            <li>
              <Link href="/menu2">
                菜单2
              </Link>
              <ul>
                <li>
                  <Link href="/menu2/submenu1">
                    子菜单1
                  </Link>
                </li>
                <li>
                  <Link href="/menu2/submenu2">
                    子菜单2
                  </Link>
                </li>
              </ul>
            </li>
            <li>
              <Link href="/menu3">
                菜单3
              </Link>
              <ul>
                <li>
                  <Link href="/menu3/submenu1">
                    子菜单1
                  </Link>
                </li>
                <li>
                  <Link href="/menu3/submenu2">
                    子菜单2
                  </Link>
                </li>
              </ul>
            </li>
            <li>
              <Link href="/menu4">
                菜单4
              </Link>
              <ul>
                <li>
                  <Link href="/menu4/submenu1">
                    子菜单1
                  </Link>
                </li>
                <li>
                  <Link href="/menu4/submenu2">
                    子菜单2
                  </Link>
                </li>
              </ul>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
